FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    calibre \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8000

COPY start.sh .
RUN chmod +x start.sh

ENV HOME=/app
RUN mkdir -p /app/.config

CMD ["./start.sh"]